
# An example of ClusterConfig object with highly available NAT gateways
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-9
  region: eu-west-2

vpc:
  nat:
    gateway: HighlyAvailable # other options: Disable, Single (default)

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    minSize: 2
    maxSize: 4
    # desiredCapacity: 2
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    iam:
      withAddonPolicies:
        # ebs: true
        efs: true # Allow the cluster nodes to interact with efs so they can manage mounts.
