
# An example of ClusterConfig object with highly available NAT gateways
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  region: eu-west-2
  name: 73d725d

vpc:
  nat:
    gateway: Single  # Valid variants are: "HighlyAvailable" configures a highly available NAT gateway, "Single" configures a single NAT gateway (default), "Disable" disables NAT.
  cidr: 10.142.0.0/16

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    minSize: 2
    maxSize: 4
    # desiredCapacity: 2
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    iam:
      withAddonPolicies:
        # ebs: true
        efs: true # Allow the cluster nodes to interact with efs so they can manage mounts.
