---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-bash
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: app
          image: public.ecr.aws/z3g6z3t0/perl:5.14.4-threaded
          command: ["/bin/bash"]
          # args: ["-c", "cd /data; while true; do dd if=/dev/zero of=$(hostname)-$(date +%s%N) oflag=direct bs=16k count=1000 2>&1 | grep bytes; done "]
          # args: ["-c", "cd /data; perl -e 'for(<*>){((stat)[9]<(unlink))}';"]
          args: ["-c", "while true; do sleep 10; done"]
          volumeMounts:
            - name: persistent-storage
              mountPath: /data
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-claim
