---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: job-root-pv
spec:
  storageClassName: efs-sc-1
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - tls
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-50d82da0
    volumeAttributes:
      path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-root-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs-sc-1
  volumeName: job-root-pv
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-efs-dir
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: $SERVICE_ACCOUNT_NAME
      containers:
        - name: aws-cli-pod
          image: amazon/aws-cli
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "cd /mnt/efs; mkdir -p $RANDOM_STRING" ]
          volumeMounts:
            - mountPath: /mnt/efs
              name: efs-volume
              readOnly: false
      volumes:
        - name: efs-volume
          persistentVolumeClaim:
            claimName: job-root-pvc
